name: action-genai-video-issue-analyzer
description: Analyzes videos upload as assets
inputs:
  instructions:
    description: Custom prompting instructions for each video.
    required: false
    default: Analyze the video and provide a summary of its content. Extract list of
      followup subissues if any. The transcript is your primary source of text
      information, ignore text in images.
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
    required: true
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
runs:
  using: docker
  image: Dockerfile
outputs:
  text:
    description: The generated text output.
