name: Continuous Integration
on:
  issues:
    types: [opened, edited]
permissions:
  contents: read
  issues: write
  models: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
  test-action:
    needs: test
    runs-on: ubuntu-latest
    services:
      whisper:
        image: onerahmet/openai-whisper-asr-webservice:latest
        env:
          ASR_MODEL: base
          ASR_ENGINE: openai_whisper
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/docs || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 20s          
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_issue: ${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          debug: "*"