name: Continuous Integration
on:
  issues:
    types: [opened, edited]
permissions:
  contents: read
  issues: write
  models: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
  test-action:
    needs: test
    runs-on: ubuntu-latest
    services:
      whisper:
        image: onerahmet/openai-whisper-asr-webservice:latest
        env:
          ASR_MODEL: base
          ASR_ENGINE: openai_whisper
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Whisper service
        run: |
          timeout=60
          elapsed=0
          while ! curl -s -I http://localhost:9000/docs > /dev/null; do
            sleep 5
            elapsed=$((elapsed + 5))
            if [ $elapsed -ge $timeout ]; then
              echo "Timeout waiting for Whisper service"
              exit 1
            fi
            echo "Waiting for Whisper service..."
          done
          echo "Whisper service is ready!"
      - uses: ./
        with:
          github_issue: ${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          debug: "*"